const mongoose = require('mongoose');

const refundRequest = new mongoose.Schema({
  // ── Core Identity ───────────────────────────────────────────
  claimId: { type: String, required: true, unique: true, index: true },
  
  // Link to the User model (ObjectId for joins, Roll for quick display)
  student: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true, index: true },
  studentRoll: { type: String, required: true, uppercase: true },
  
  // ── Categorization ──────────────────────────────────────────
  requestType: { 
    type: String, 
    enum: ['FEST_REIMBURSEMENT', 'MESS_REBATE', 'MEDICAL_REBATE'],
    required: true,
    index: true
  },
  
  // Optional Fest-Specific Fields
  festName: { type: String, trim: true },
  teamName: { type: String, trim: true },
  
  // ── Details & Financials ────────────────────────────────────
  title:       { type: String, required: true, trim: true }, // Short summary (e.g., "TechFest Speaker Travel")
  description: { type: String, required: true, trim: true },
  amount:      { type: Number, required: true, min: 0 },
  
  transactionId: { 
    type: String, 
    unique: true, // 👈 THE MAGIC SHIELD
    sparse: true, // Allows Mess Rebates to NOT have a transaction ID
    validate: {
      validator: function(v) {
        if (!v) return true; // Skip if empty
        return /^\d{12}$/.test(v); // Double-checks the 12 digits on the server
      },
      message: props => `${props.value} is not a valid 12-digit Transaction ID!`
    }
  },

  // ── Supporting Documents (Upgraded for Cloudinary) ──────────
  attachments: [{
    filename:    { type: String },
    url:         { type: String, required: true }, // The Cloudinary URL
    mimetype:    { type: String },
    uploadedAt:  { type: Date, default: Date.now },
  }],
  
  // ── Workflow Engine ─────────────────────────────────────────
  status: { 
    type: String, 
    enum: [
      'PENDING_TEAM_COORD', 
      'PENDING_FEST_COORD', 
      'PENDING_MESS_MANAGER',
      'PENDING_VP', 
      'PENDING_ACADEMIC', 
      'APPROVED', 
      'REJECTED', 
      'REFUNDED'
    ],
    required: true,
    index: true
  },
  
  // ── Audit Trail (Multi-step History) ────────────────────────
  history: [{
    action:   { type: String, required: true }, // e.g., "SUBMITTED", "APPROVED_BY_TEAM_COORD"
    byUser:   { type: mongoose.Schema.Types.ObjectId, ref: 'User' }, // Links to the admin who did it
    byName:   { type: String }, // Human-readable name for fast UI loading
    date:     { type: Date, default: Date.now },
    comments: { type: String, trim: true } // e.g., "Receipt blurry, rejected"
  }],

  // ── Final Disbursement Details ──────────────────────────────
  disbursedAt:     { type: Date, default: null },
  disbursedAmount: { type: Number, default: null },
  disbursementRef: { type: String, default: null }, // UTR generated by Accounts when finally paid

}, { timestamps: true });

// ── Database Indexes (For high-performance queries) ───────────
// These make your dashboard load instantly even with 10,000+ claims
refundRequest.index({ status: 1, requestType: 1 });
refundRequest.index({ student: 1, createdAt: -1 });

// ✅ SAFE EXPORTS (Prevents OverwriteModelError)
module.exports = mongoose.models.RefundRequest || mongoose.model('RefundRequest', refundRequest);